Raw Analysis of West Washington Park Neighborhood Crime Data
========================================================

Set up required libraries:

```{r}
library(data.table)
library(zoo)
library(ggplot2)
```

Processing
----------

Download the data file, read the data and save a .rda file.

```{r}
use_cached = TRUE
csv_file = '../data/crime.csv'
rda_file = '../data/crimeRaw.rda'
# Use cached file because it's a big download
if (!file.exists(csv_file) && !useCached) {
  crimeURL <- "http://data.denvergov.org/download/gis/crime/csv/crime.csv"
  download.file(crimeURL,destfile=csv_file,method="curl")
  downloadTimestamp <- date()
} else {
  downloadTimestamp <- file.info(csv_file)$ctime
}
if (!file.exists(rda_file) && !useCached) {
  crime <- read.csv(csv_file)
  crime <- data.table(crime)
  save(crime, downloadTimestamp, file = '../data/crimeRaw.rda')
} else load(rda_file)
```
Looking at the basic structure...
```{r}
summary(crime)
```

Clean up data
-------------

Get the information about when a crime was reported into a more usable format

```{r}
crime <- crime[,REPORTED_DATE:=as.POSIXct(REPORTED_DATE,format="%Y-%m-%d %H:%M:%S",tz='MST')]
crime <- crime[,FIRST_OCCURRENCE_DATE:=as.POSIXct(FIRST_OCCURRENCE_DATE,format="%Y-%m-%d %H:%M:%S",tz='MST')]
crime <- crime[,year_month:=as.yearmon(format(FIRST_OCCURRENCE_DATE))]
```

Big Picture
-----------

Time frame for the data

```{r}
min(crime$REPORTED_DATE)
max(crime$REPORTED_DATE)
```

Look at # of reports per neighborhood over the last 12 months

```{r, fig.width=12, fig.height=18}
year_ago = max(crime$year_month)-1
crime_last_12_months = crime[year_month >= year_ago]
crime_by_neighborhood = sort(table(crime_last_12_months$NEIGHBORHOOD_ID),decreasing=TRUE)
title = paste("Police Reports by Neighborhood:",format(year_ago),"to Present")
dotchart(crime_by_neighborhood, labels=names(crime_by_neighborhood), main=title, 
         xlab="# of Reports (source: data.denvergov.org)",cex=0.7)
```

Drill down a little bit

```{r, fig.width=12}
wwp_crime = crime[NEIGHBORHOOD_ID=='washington-park-west']
wwp_crimes_by_month = table(wwp_crime$year_month)
plot(wwp_crimes_by_month,xaxt='n',type='p')
axis(side=1,las=2,labels=names(wwp_crimes_by_month),at=1:length(wwp_crimes_by_month),cex.axis=0.8)
```

```{r, fig.width=12, fig.height=12}
wwp_thefts = wwp_crime[(OFFENSE_CATEGORY_ID=='burglary' | OFFENSE_CATEGORY_ID=='theft-from-motor-vehicle' | OFFENSE_CATEGORY_ID == 'auto-theft') & OFFENSE_TYPE_ID != 'burglary-business-by-force' & OFFENSE_TYPE_ID != 'burglary-business-no-force' & OFFENSE_TYPE_ID != 'theft-parts-from-vehicle']
ggplot(wwp_thefts,aes(factor(year_month),fill=OFFENSE_TYPE_ID)) + geom_bar() + facet_wrap(~OFFENSE_TYPE_ID) + theme(axis.text.x=element_text(size=6,angle=-90),legend.position='none') + ggtitle("West Wash Park Burglaries By Month") + scale_y_continuous(breaks=0:10) + xlab('Month') + ylab('Number of Burglaries')
```

```{r, fig.width=12}
ggplot(wwp_thefts,aes(factor(year_month),fill=OFFENSE_TYPE_ID)) + geom_bar() + theme(axis.text.x=element_text(size=8,angle=-90)) + scale_y_continuous(breaks=0:25) + xlab('Month') + ylab('Number of Burglaries')
```
